from __future__ import annotations

import argparse
import hashlib
import re
import tempfile
from pathlib import Path, PurePosixPath


EXPECTED_VERSION = "2026c"
EXPECTED_IDS = 488
EXPECTED_FIXED = 43
EXPECTED_ZONES = 445
EXPECTED_BYTES = 470_144
FIXED_RE = re.compile(r"UTC[+-]\d{2}:\d{2}\Z")


def read_ids(t1_log: Path | None, ids_path: Path | None) -> list[str]:
    if (t1_log is None) == (ids_path is None):
        raise ValueError("exactly one of --t1-log and --ids is required")
    if t1_log is not None:
        values = [
            match.group(1)
            for line in t1_log.read_text(encoding="utf-8").splitlines()
            if (match := re.fullmatch(r"qt_zone=([^|]+)\|.*", line)) is not None
        ]
    else:
        values = ids_path.read_text(encoding="utf-8").splitlines()  # type: ignore[union-attr]
    if len(values) != EXPECTED_IDS or len(set(values)) != EXPECTED_IDS:
        raise ValueError(f"expected {EXPECTED_IDS} unique IDs, got {len(values)}/{len(set(values))}")
    return sorted(values, key=lambda value: value.encode("utf-8"))


def is_fixed(value: str) -> bool:
    return FIXED_RE.fullmatch(value) is not None


def zone_path(root: Path, identifier: str) -> Path:
    relative = PurePosixPath(identifier)
    if relative.is_absolute() or ".." in relative.parts or "." in relative.parts:
        raise ValueError(f"unsafe zone ID: {identifier!r}")
    candidate = root.joinpath(*relative.parts)
    try:
        candidate.resolve().relative_to(root.resolve())
    except ValueError as error:
        raise ValueError(f"zone escaped root: {identifier!r}") from error
    return candidate


def render_inc(ids: list[str], payloads: list[tuple[str, bytes]]) -> bytes:
    combined = bytearray()
    entries: list[tuple[str, int, int]] = []
    for identifier, payload in payloads:
        offset = len(combined)
        combined.extend(payload)
        entries.append((identifier, offset, len(payload)))
    lines = ["// Generated by generate_bundled_tzdata.py. Do not edit.",
             "constexpr unsigned char kBundledTzdataBytes[] = {"]
    for index in range(0, len(combined), 16):
        chunk = combined[index:index + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(("};", "constexpr S_BUNDLED_ZONE_ENTRY kBundledZones[] = {"))
    lines.extend(f'    {{"{name}", {offset}, {length}}},' for name, offset, length in entries)
    lines.extend(("};", "constexpr std::string_view kSupportedTimeZoneIds[] = {"))
    lines.extend(f'    "{identifier}",' for identifier in ids)
    lines.extend(("};", ""))
    return "\n".join(lines).encode("ascii")


def generate(
    ids: list[str], zoneinfo_root: Path, copyright_source: Path,
    output_inc: Path, output_dir: Path,
) -> None:
    zi_lines = zoneinfo_root.joinpath("tzdata.zi").read_text(encoding="ascii").splitlines()
    version_line = zi_lines[0]
    match = re.fullmatch(r"# version (\S+)", version_line)
    if match is None or match.group(1) != EXPECTED_VERSION:
        raise ValueError(f"expected tzdata {EXPECTED_VERSION}, got {version_line!r}")
    fixed = [value for value in ids if is_fixed(value)]
    named = [value for value in ids if not is_fixed(value)]
    if len(fixed) != EXPECTED_FIXED or len(named) != EXPECTED_ZONES:
        raise ValueError(f"classification drift: fixed={len(fixed)} named={len(named)}")
    links = {fields[2]: fields[1] for line in zi_lines
             if len(fields := line.split()) == 3 and fields[0] == "L"}

    payloads: list[tuple[str, bytes]] = []
    manifest: list[str] = []
    total = 0
    for identifier in named:
        current = identifier
        visited: set[str] = set()
        while True:
            path = zone_path(zoneinfo_root, current)
            try:
                payload = path.read_bytes()
            except OSError:
                payload = b""
            if payload.startswith(b"TZif"):
                break
            if payload:
                raise ValueError(f"non-TZif payload: {identifier}")
            if current in visited or current not in links:
                raise ValueError(f"missing TZif file: {identifier}")
            visited.add(current)
            current = links[current]
        if not payload.startswith(b"TZif"):
            raise ValueError(f"non-TZif payload: {identifier}")
        payloads.append((identifier, payload))
        total += len(payload)
        manifest.append(f"{identifier}\t{len(payload)}\t{hashlib.sha256(payload).hexdigest()}")
    if total != EXPECTED_BYTES:
        raise ValueError(f"payload total drift: expected {EXPECTED_BYTES}, got {total}")

    output_dir.mkdir(parents=True, exist_ok=True)
    output_inc.parent.mkdir(parents=True, exist_ok=True)
    output_dir.joinpath("VERSION").write_text(EXPECTED_VERSION + "\n", encoding="ascii", newline="\n")
    output_dir.joinpath("COPYRIGHT").write_bytes(copyright_source.read_bytes())
    output_dir.joinpath("QT_AVAILABLE_IDS.txt").write_text("\n".join(ids) + "\n", encoding="ascii", newline="\n")
    output_dir.joinpath("MANIFEST.tsv").write_text("\n".join(manifest) + "\n", encoding="ascii", newline="\n")
    output_inc.write_bytes(render_inc(ids, payloads))


def main() -> int:
    parser = argparse.ArgumentParser()
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--t1-log", type=Path)
    source.add_argument("--ids", type=Path)
    parser.add_argument("--zoneinfo-root", required=True, type=Path)
    parser.add_argument("--copyright-source", required=True, type=Path)
    parser.add_argument("--output-inc", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    ids = read_ids(args.t1_log, args.ids)
    if not args.check:
        generate(ids, args.zoneinfo_root, args.copyright_source, args.output_inc, args.output_dir)
        return 0
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        generated_dir = root / "2026c"
        generated_inc = root / "bundled.inc"
        generate(ids, args.zoneinfo_root, args.copyright_source, generated_inc, generated_dir)
        pairs = [(generated_inc, args.output_inc)] + [
            (generated_dir / name, args.output_dir / name)
            for name in ("VERSION", "COPYRIGHT", "QT_AVAILABLE_IDS.txt", "MANIFEST.tsv")
        ]
        mismatches = [str(tracked) for generated, tracked in pairs
                      if not tracked.is_file() or generated.read_bytes() != tracked.read_bytes()]
        if mismatches:
            raise RuntimeError("generated output mismatch: " + ", ".join(mismatches))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
