from __future__ import annotations

import argparse
import tempfile
import unicodedata
from pathlib import Path


VERSION = "15.1.0"
EXPECTED_ENTRIES = 1_530
EXPECTED_SCALARS = 1_650
EXPECTED_MAX = 3


def render() -> bytes:
    if unicodedata.unidata_version != VERSION:
        raise RuntimeError(f"expected Unicode {VERSION}, got {unicodedata.unidata_version}")
    entries: list[tuple[int, int, int]] = []
    mapped: list[int] = []
    maximum = 0
    for scalar in range(0x110000):
        if 0xD800 <= scalar <= 0xDFFF:
            continue
        folded = tuple(ord(value) for value in chr(scalar).casefold())
        if folded == (scalar,):
            continue
        entries.append((scalar, len(mapped), len(folded)))
        mapped.extend(folded)
        maximum = max(maximum, len(folded))
    if (len(entries), len(mapped), maximum) != (EXPECTED_ENTRIES, EXPECTED_SCALARS, EXPECTED_MAX):
        raise RuntimeError(f"metadata drift: {len(entries)}/{len(mapped)}/{maximum}")
    lines = ["// Generated by generate_python_casefold_table.py. Do not edit.",
             f'constexpr std::string_view kPythonCasefoldUnicodeVersion = "{VERSION}";',
             f"constexpr std::size_t kPythonCasefoldEntryCount = {len(entries)};",
             f"constexpr std::size_t kPythonCasefoldMappedScalarCount = {len(mapped)};",
             f"constexpr std::size_t kPythonCasefoldMaximumExpansion = {maximum};",
             "constexpr S_CASEFOLD_ENTRY kPythonCasefoldEntries[] = {"]
    lines.extend(f"    {{0x{scalar:06x}, {offset}, {length}}}," for scalar, offset, length in entries)
    lines.append("};")
    lines.append("constexpr std::uint32_t kPythonCasefoldMappedScalars[] = {")
    for index in range(0, len(mapped), 12):
        lines.append("    " + ", ".join(f"0x{value:06x}" for value in mapped[index:index + 12]) + ",")
    lines.extend(("};", ""))
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if not args.check:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(content)
        return 0
    with tempfile.TemporaryDirectory() as temporary:
        generated = Path(temporary) / "casefold.inc"
        generated.write_bytes(content)
        if not args.output.is_file() or generated.read_bytes() != args.output.read_bytes():
            raise RuntimeError(f"generated output mismatch: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
