//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// 다음에서 사용 NoteEx.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_NOTEEX_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDM_RESET_GEOMETRY		106
#define IDI_NOTEEX			107
#define IDI_SMALL				108
#define IDC_NOTEEX			109
#define IDM_NEW_WINDOW			110
#define IDM_NEW_DOCUMENT		111
#define IDM_DOCUMENT_LIST		112
#define IDM_GLOBAL_SEARCH		113
#define IDM_IMPORT_TEXT			114
#define IDM_EXPORT_TEXT			115
#define IDM_CREATE_BACKUP		116
#define IDM_RESTORE_BACKUP		117
#define IDM_SAVE_CARD			118
#define IDM_FIND				119
#define IDM_REPLACE			120
#define IDM_CARD_LIST			121
#define IDM_HISTORY				122
#define IDM_BACK				123
#define IDM_FOCUS_MODE			124
#define IDM_SETTINGS			125
#define IDM_DATA_LOCATION		126
#define IDM_LICENSES			127
#define IDM_FIRST_RUN_GUIDE		131
#define IDC_DOCUMENT_CARD_LIST	2101
#define IDC_DOCUMENT_EDITOR		2102
#define IDC_DOCUMENT_FIND		2103
#define IDC_DOCUMENT_REPLACE	2104
#define IDC_DOCUMENT_HISTORY	2105
#define IDC_MAIN_STATUS			2106
#define IDC_SEARCH_QUERY		2107
#define IDC_DOCUMENT_SHELL_LIST	2108
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// 다음은 새 개체에 사용할 기본값입니다.
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32772
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
